Feature/aot 999 layer builds
Skatteetaten/architect pull request #107
Opened 2020-07-10 06:52 UTC by bj0rn

2020-07-10 06:57 UTC, bj0rn commented
Det er fortsatt en del ting som må justeres på. Den største funksjonaliteten som mangler er muligheten for retag med den nye byggeren. Dette er ikke noe jeg har tatt hensyn til i denne omgang.

Det er også nødvendig å justere litt på strukturen. Det er ikke alt der jeg er like fornøyd med. Det er bare å komme med forslag til forbedringer :)

2020-10-12 10:47 UTC, bj0rn commented on pkg/doozer/prepare/prepare.go
> +	err = os.Symlink(target, buildContext+"/layer/u01/application/logs")
De skal være korrekt. Når de er feil vil ikke applikasjonene starte. Det tok en del forsøk på å forstå hvordan det vil se ut i den kjørende containeren.

2020-10-12 10:56 UTC, nixx requested changes
Det er lovende.

Testscript må fikses.

2020-10-12 11:15 UTC, bj0rn commented on pkg/docker/registry.go
>  package docker
Skal sjekke den ut

2020-10-13 07:40 UTC, bj0rn commented on pkg/config/types.go
> +	Layer = "layer"
Det har du helt rett i. Fjernet

2020-10-13 07:41 UTC, bj0rn commented on pkg/config/config.go
> +		pullRegistry = fmt.Sprintf("https://%s:443", pullRegistry)
Fjernet

2020-10-13 07:41 UTC, bj0rn commented on pkg/config/config.go
> +	var buildStrategy = Layer
Slettet

2020-10-13 07:44 UTC, bj0rn commented on pkg/docker/utils.go
>  	}
Fikset

2020-10-14 08:28 UTC, RuneOfferdal commented
I Readme.md må kapitlet "How to build Architect?" skrives om for å matche ny bygging.

2020-10-15 09:29 UTC, bj0rn commented
> I Readme.md må kapitlet "How to build Architect?" skrives om for å matche ny bygging.
Det er mye som må skrives om der. Jeg noterer det ned på blokka mi :)

2020-10-16 13:59 UTC, RuneOfferdal reviewed
Sjekk gjennom kommentarer.  Kan hende det meste er OK. Avventer godkjenning.

2020-10-16 13:59 UTC, RuneOfferdal commented on pkg/docker/registry.go
> +func (registry *RegistryClient) LayerExists(ctx context.Context, repository string, layerDigest string) (bool, error) {
Trenger man virkelig to returverdier her? Kan ikke return false, nil erstattes med en error?

2021-01-29 09:40 UTC, closed without merging