AOT-1094 Generate splunk stanza
Skatteetaten/architect pull request #108
Opened 2020-10-19 15:03 UTC by bj0rn

2020-10-20 07:30 UTC, bj0rn commented on pkg/doozer/prepare/dockerfile.go
> +/u01/bin/radish generateSplunkStanzas -o /u01/logs
@nixx  Skal jeg legge inn $(/u01/bin/radish generateEnvScript) også ?

2020-10-21 08:48 UTC, nixx requested changes
Fint om selve scriptet flyttes til imaget. Radish må likevel ligge der, og vi ønsker ikke spre ting for mye.

Hvis du ønsker å ha mulighet for både å sette cmd direkte, samt å bruke en wrapper, så kan du  gjøre oppslag på annoteringer på baseimaget, for å se hva den kan tilby. F.eks. en annotering "skatteetaten.no/startupWrapper"

2020-10-21 08:48 UTC, nixx commented on pkg/doozer/prepare/dockerfile.go
> +/u01/bin/radish generateSplunkStanzas -o /u01/logs
Flytt denne til imaget isteden. Det er mye lettere å endre det der.

2020-10-22 05:44 UTC, bj0rn commented on pkg/doozer/prepare/dockerfile.go
> +/u01/bin/radish generateSplunkStanzas -o /u01/logs
Flyttet til flex

2020-11-05 08:51 UTC, nixx approved these changes
Dette skjer kun på Doozer-leveranse, så vi får testet det godt.

Godkjenner under forutsetnig at du får testet de applikasjonene det er snakk om. Det bør være mulig.

2020-11-05 11:22 UTC, merged