Feature/aos 6411 api for binary build
Skatteetaten/architect pull request #143
Opened 2022-03-24 07:59 UTC by kris456

Jeg ser ikke helt verdien av testing av denne. Hvis noen mener noe annet, kom gjerne med innspill i hvordan det bør testes.

2022-03-24 08:36 UTC, kris456 commented
Skal få fikset jenkins feil

2022-03-24 08:51 UTC, bj0rn commented on go.mod
>  go 1.16
Kam du bumpe til 1.18 ?

2022-03-24 08:52 UTC, bj0rn commented on go.mod
>  go 1.16
Fint om du samtidig bumper alle pakker og rydder i avhengigheter

2022-03-24 08:53 UTC, kris456 commented on go.mod
>  go 1.16
done

2022-03-24 08:53 UTC, kris456 commented on go.mod
>  go 1.16
Skal ta en titt over avhengighetene

2022-03-24 08:53 UTC, bj0rn commented on pkg/build/build.go
> +	var binaryInput string
Denne er ikke nødvendig

2022-03-24 12:15 UTC, kris456 commented on pkg/build/build.go
> +	var binaryInput string
Jeg fjernet den, men mulig jeg ikke ser noe nå. Hvordan skal da architect få tak i filen?

2022-03-24 12:15 UTC, bj0rn approved these changes

2022-03-24 12:48 UTC, furode approved these changes

2022-03-25 11:54 UTC, stromland requested changes

2022-03-25 11:54 UTC, stromland commented on pkg/build/build.go
> +	const internalPullRegistry = "https://container-registry-internal-private-pull.aurora.skead.no"
Flytte denne til au?

2022-03-25 11:57 UTC, kris456 commented on pkg/build/build.go
> +	const internalPullRegistry = "https://container-registry-internal-private-pull.aurora.skead.no"
Ja det kan jeg vel egentlig

2022-03-25 11:58 UTC, kris456 commented on pkg/build/build.go
> +	const internalPullRegistry = "https://container-registry-internal-private-pull.aurora.skead.no"
Fikset

2022-03-25 11:59 UTC, stromland approved these changes

2022-03-25 14:55 UTC, merged